{% set name = "google-auth-httplib2" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/google-auth-library-python-httplib2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7e714ff7a4cd6c69b76f8c91dfe177cdce49ae8bfb398b22a7c1468f3915037d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - google-auth
    - httplib2 >=0.19.0
    - six

test:
  source_files:
    - tests
  imports:
    - google_auth_httplib2
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - flask
    - pytest-cov
    - pytest-localserver

about:
  home: https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Authentication Library httplib2 transport
  description: This library provides an httplib2 transport for google-auth. Note that httplib has lots of problems such as lack of threadsafety and insecure usage of TLS. Using it is highly discouraged. This library is intended to help existing users of oauth2client migrate to google-auth.
  doc_url: https://google-auth.readthedocs.io
  dev_url: https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - theacodes
    - tswast
