{% set name = "google-auth-httplib2" %}
{% set version = "0.0.4" %}
{% set sha256 = "8d092cc60fb16517b12057ec0bba9185a96e3b7169d86ae12eae98e645b7bc39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python

  run:
    - python
    - google-auth
    - httplib2 >=0.9.1
    - six

test:
  imports:
    - google_auth_httplib2

about:
  home: https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Authentication Library httplib2 transport
  description: This library provides an httplib2 transport for google-auth. Note that httplib has lots of problems such as lack of threadsafety and insecure usage of TLS. Using it is highly discouraged. This library is intended to help existing users of oauth2client migrate to google-auth.
  doc_url: https://google-auth.readthedocs.io/en/latest/
  dev_url: https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - theacodes
    - tswast
