travis:
  secure:
    BINSTAR_TOKEN: R/nY5oH6nNEJVTmEutDt+k2WHTRtU+4+9HTaxs3vdpLWRpBPwknhobru3sz22HWRiPVuy6X8bjSl4dP5Gi1gX5LZ3p52PkzBNh7+BfGYW98j3/jvEyBfEv9lUrIYaokh4aUspbnRGePUTkCFnis3231kTtD2Y5so+dnkEAzHSAIk60sR2i0/ojHGg/s3nW4EOtv+63Mt0jr4b9c4F0AScoW2duEMqiUgO1SJFOlOVKFhL4Aqc1L59qR9VzYYk1o70KSCDX2+XRDCLKcStVN0a6Ofxzq60rWdn0MnRgbiXZ/QhxKk0hJjAHO8YwqyDymWYemVs88RP4mS6HKNMv236aElUB03Om/ke5Ytzs5MLyNIm3sD+gSBKwhFcPbRroqDQ/e+fKsP5cfHMVSD2bfvjMuXXDM1aDWfle1iWzOPpEzUEbhHhnUBvNQ0UIJTkQ7gKeKPRufltu1Xvz0TQEr5zhLCvqIKK6vh20WkLL0edLTxRUibT5/qUxXDwQD+fd/8eePj15uGTb+Mm/4QBXnMD9U1etuBYCP1ArKbgjUhdLNHmSegZ/t18chQkxeokF+HM20D09ig9MCtcpjR8SNG0WDPSeHrzwI/D22s/IsilYwVa/vw0rK+WC9ycG0IkAFC/JkhZ+aqPA+PdX8Psj6CawnPTI9/wJYVjDgXk/GrJRw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
