travis:
  secure:
    BINSTAR_TOKEN: b4HU9mS58sxb57GV2iUoLV2fBhiXVT3CHFXROP6P8stqnMbZnaFQWe0cGwHlKkFMAqdOKu5867iziMtMqOA1PW3Le5eMi3CSs6BZJdn2jcVEILmz2hqk2D4PyOOzNc13nwh+u74Rsi7PjosGGBpIMZaWCH7wXR8rjIIfs66dTFLXIopFfb8avnevW1gXnjdohgMTFR0rhEnmoTaPtxulmg622+/CbM9SivlZDXhmpOZIuf2+gVgn+rpmBolJVuYoR7QovTq22gGUwC6pXToyNvNswwYPr5AklvKwMk18bginSBGiqunSvPSZ1NEJBHUAcBHFc+e1ymI3ug9SIaGa3n/NPDN94HdLK9wtdKlPGjtux2tpSTRHZoWzyRr/CqQ2NIrvsbFM1MehF7vVjKVoGrC7lycXd7/O5Nb+Z3buHB0n6dWzZ0qfnvmQwaNzmlwG8SkXgFBPDI1+e8yWpeRe2R5aeGQS+J9IqwFajuAz4E/KjMNrqnFgpaAckFNY0iUCRApb74cQ24IY3U5pSD7kz5Y1cXsR0eJBGAzwNnoauJfH1Z9F28HNyENpa8Y63MHliOBAQL8VAV5Ba94+p28vkPHPtwh7g2H/SnF8Cjkt5ijLNlqYIIIBmxe3nOiRgLMmke2eMdD2Xq5/8N+AHQTB6sR2uARKGFCXcsTdq8w6cDk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
