travis:
  secure:
    BINSTAR_TOKEN: C39WKE/hmZSu5nFV2WHDpYpIacqxWlh0drSELxdcK5dvGahwJDTcJTKDxAbq2O2xJcY9w8EA4tLP6BwxzwTVWnwkCOtE3UY6/LGPNYulhLqSkynldzPA8TDhEXdTCPB8QAO8iR8Us4BV1Q/UT0TpsiYSJfB1MCuY1NZahsfd5vc4VsqIQDhtClYFYPnEZV4DehydMwN93PqngyRb3tUFX3Mq12xUQ6IPWMRv/BpGDgCsVBsFBb24cehW4XLKxX3CvPpIiLPAWdunzLdLejqI5gHzXXB0u/QTxpVQzHUxKtMFsVYBxurFykdmEZI/Qw9TLGZXCEl0WX1W2LsieBxrSjKpTn21FZKCjap/Yga98pmJ3jaSQ9V1wXDY6jRtmfN8K0ZFJGNX42mpumObzB+khMIl5/DtRTCMsrn6tcy1bIiDZ8yQX0YJl9WH8MekykMXWJtmmuV+t+SliI+DMIs5vcGDgk+yfukKIoFSOInsikrF6S5Cg8CtYSLjbDNpwXYoWfz9EnP6/Eq+GKKTFlYUlOK3u63BB+8WLZOxuztDuaoRunp0AHiRgKr/5ywg8MZiYeTJ7zO28qO88557mhXYSSzCAfHp82rkLhohgVVsBDvy/l2/oRxM7MdJjdeyg5/yPg8NF+zmchDKCbk334fp1rGosjQK94qM+SJM4kJVbtM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
